# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[context.production]
  environment = { NODE_VERSION = "14.15.3" }
