[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[context.production]
  environment = { NODE_VERSION = "14.15.3" }
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
